name: Build and Test

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7, 3.8, 3.9]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install poetry
        make deps
    - name: Lint with flake8, pydocstyle
      run: |
        make test
    - name: Test with pytest
      run: |
        poetry run pytest
    - name: Test examples
      run: |
        poetry build
        pip install -U pip setuptools
        make examples
